# Fast local runtime defaults
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:strasbourg;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.devservices.enabled=false
quarkus.oidc.enabled=false

# PostgreSQL production profile
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USERNAME:strasbourg}
%prod.quarkus.datasource.password=${DB_PASSWORD:strasbourg}
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/strasbourg}
%prod.quarkus.oidc.enabled=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:strasbourg;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.devservices.enabled=false
%test.quarkus.oidc.enabled=false
