package com.pswied.loan.strasbourg.domain.loanorigination;

public enum LoanOriginationDecisionReasonCode {
    ALL_CHECKS_PASSED,
    ELIGIBILITY_INELIGIBLE,
    ELIGIBILITY_MANUAL_REVIEW_REQUIRED,
    APPLICANT_REJECTED,
    MERCHANT_REJECTED,
    APPLICANT_MANUAL_REVIEW_REQUIRED,
    MERCHANT_MANUAL_REVIEW_REQUIRED
}
